---
- hosts: mywebservers
  become: yes
  tasks:

  - name: i am installing java on ubuntu 16.04
    apt:
     name: "{{myjavaonubunt}}"
     state: present 
    when:  ansible_os_family== "Debian"

  - name: i am installing java on RedHat
    yum:
     name: "{{myjavaonredhat}}"
     state: present 
    when:  ansible_os_family== "RedHat"
