---
- hosts: myubuntuservers
  become: yes
  tasks:

  - name: i want to install webserver
    apt: 
      name: apache2
      state: present

  - name: Change index page
    template:
      src: myindex.j2
      dest: /var/www/html/index.html