---
- hosts: mywebservers
  become: yes
  tasks:

  - name: i am installing java on ubuntu 16.04
    apt:
     name: [openjdk-8-jre]
     state: present 
    when:  ansible_os_family== "Debian"

  - name: i am installing java on RedHat
    yum:
     name: [java-1.8.0-openjdk]
     state: present 
    when:  ansible_os_family== "RedHat"
