---
- hosts: myubuntuservers
  become: yes
  tasks:

  - name: install multi packeges
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - tree
      - git
      - wget
    when: ansible_os_family== "Debian"
      