---
- name: deploy
  get_url: 
    url: https://newbucketsumitnew.s3.us-east-2.amazonaws.com/mahalogin-master.zip
    dest: /opt/tomcat/webapps/mahaLogin.war
    force_basic_auth: yes


- name: deploy_jenkin_server
  get_url: 
    url: https://get.jenkins.io/war-stable/2.263.1/jenkins.war
    dest: /opt/tomcat/webapps/jenkins.war
    force_basic_auth: yes

    