---
- name: change group
  command: sudo chgrp -R tomcat /opt/tomcat

- name: change group
  command: sudo chmod -R g+r conf

- name: change group
  command: sudo chmod g+x conf

- name: change group
  command: sudo chown -R tomcat webapps/ work/ temp/ logs/

